#!/usr/bin/env bash
set -euo pipefail
MODEL_KEY="qwen3_4b"; MODEL="${MODEL:-/workspace/storage-shared/models/Qwen3-4B}"
DATASET="${DATASET:-gsm8k}"; DRAFT_CHECKPOINT="${DRAFT_CHECKPOINT:-}"
TARGET_LR="${TARGET_LR:-1e-6}"; DRAFT_LR="${DRAFT_LR:-1e-6}"
BATCH_SIZE="${BATCH_SIZE:-8}"; ACCUMULATION_STEPS="${ACCUMULATION_STEPS:-4}"
GEN_MAX_LENGTH="${GEN_MAX_LENGTH:-2048}"; MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-2048}"
NUM_EPOCHS="${NUM_EPOCHS:-1}"; NPROC_PER_NODE="${NPROC_PER_NODE:-1}"
REFLEX_MODE="${REFLEX_MODE:-off}"; REFLEX_FEATURE_DIM="${REFLEX_FEATURE_DIM:-8}"
REFLEX_LR="${REFLEX_LR:-0.05}"; REFLEX_WEIGHT_DECAY="${REFLEX_WEIGHT_DECAY:-0.0}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/scripts/launch/train_model.sh"
